name: SizeUI
main: Minetron26\Size_PlayOver\SizeUI
version: 0.0.1
api: 3.1.0
load: POSTWORLD
author: Minetron26
description: Plugin developed by Minetron26.
website: http://playover.cf
commands:
 size:
  description: "SizeUI!"
  usage: "/size"
  permission: size.minetron
permissions:
 size:
  default: op
  description: "Permission for plugin SizeUI by Minetron26"
  children:
   size.minetron:
    default: op
    description: "Allows the use of /size"
